import { Anchor, Compass, Heart, ShieldCheck, Users, Waves } from 'lucide-react'
import PageHero from '../components/PageHero'
import SectionHeader from '../components/SectionHeader'
import CTASection from '../components/CTASection'
import { media } from '../data/media'
import { team } from '../data/content'

export default function About() {
  return <><PageHero eyebrow="Rooted in Mirissa" title="For people who feel pulled to the ocean." copy="A temporary brand story, ready to be replaced with the real people, history and purpose behind your business." image={media.boat}/><section className="section"><div className="container story-grid"><div><SectionHeader eyebrow="Our story" title="Born from a love of the southern coast"/><p className="lead">Mirissa Ocean Adventures is being shaped as a modern, responsible way to experience Sri Lanka’s ocean—personal enough to feel special and professional enough to feel at ease.</p><p>This copy is intentionally provisional. Add the founder’s story, local connection and genuine experience here before launch.</p></div><div className="story-image"><img src={media.coastline} alt="Mirissa coastline"/><span><Waves/> Explore above. Dive below.</span></div></div></section><section className="section section--sand"><div className="container"><SectionHeader eyebrow="What guides us" title="Good days on the water begin with good decisions" align="center"/><div className="principles-grid">{[[Users,'Keep it personal','Smaller groups allow better support and a calmer experience.'],[ShieldCheck,'Prepare properly','Briefings, equipment checks and conditions shape every departure.'],[Heart,'Protect the wild','An encounter is only meaningful when wildlife stays undisturbed.'],[Compass,'Share local perspective','The coast is more vivid when you understand what you are seeing.']].map(([Icon,t,c])=><article key={t}><Icon/><h3>{t}</h3><p>{c}</p></article>)}</div></div></section><section className="section"><div className="container"><SectionHeader eyebrow="Your crew" title="Calm guidance. Local knowledge." copy="Names, profiles and credentials below are placeholders pending confirmed staff details."/><div className="team-grid team-grid--large">{team.map(x=><article key={x.role}><img src={x.image} alt={`${x.role} placeholder portrait`}/><div><small>{x.role}</small><h3>{x.name}</h3><p>{x.detail}</p></div></article>)}</div></div></section><CTASection/></>
}
