import { useState } from 'react'
import { ArrowLeft, ArrowRight, CalendarDays, Check, Minus, Plus, ShieldCheck } from 'lucide-react'
import { useSearchParams } from 'react-router-dom'
import PageHero from '../components/PageHero'
import { experiences } from '../data/experiences'
import { packages } from '../data/packages'
import { getPriceForGuests } from '../utils/pricing'

const steps = ['Experience', 'Date', 'Guests', 'Extras', 'Your details', 'Summary']
const extras = [['pickup', 'Hotel pickup'], ['private', 'Private option request'], ['photos', 'Underwater photography request']]

export default function Booking() {
  const [params] = useSearchParams()
  const initial = params.get('experience') || params.get('package') || experiences[0].slug
  const [step, setStep] = useState(0)
  const [done, setDone] = useState(false)
  const [form, setForm] = useState({ selection: initial, date: params.get('date') || '', adults: Number(params.get('guests')) || 2, children: 0, extras: [], name: '', email: '', phone: '', hotel: '', requests: '' })
  const options = [...experiences.map((item) => ({ ...item, type: 'Experience' })), ...packages.map((item) => ({ ...item, shortTitle: item.title, type: 'Package' }))]
  const selected = options.find((item) => item.slug === form.selection) || options[0]
  const guestCount = form.adults + form.children
  const calculatedPrice = getPriceForGuests(selected, guestCount)
  const confirmedPrice = calculatedPrice.status === 'confirmed'
  const toggle = (id) => setForm({ ...form, extras: form.extras.includes(id) ? form.extras.filter((item) => item !== id) : [...form.extras, id] })
  const next = () => setStep(Math.min(step + 1, 5))
  const back = () => setStep(Math.max(step - 1, 0))

  return <><PageHero compact eyebrow="Six simple steps" title="Your next adventure starts here." copy="Build a request now. Availability is confirmed personally—no payment is taken." /><section className="booking-section"><div className="container">
    <div className="stepper">{steps.map((label, index) => <div key={label} className={`${index === step ? 'active' : ''} ${index < step ? 'complete' : ''}`}><span>{index < step ? <Check /> : index + 1}</span><small>{label}</small></div>)}</div>
    {done ? <div className="booking-confirm"><div><Check /></div><span className="eyebrow">Request prepared</span><h2>Thanks, {form.name || 'ocean explorer'}.</h2><p>This demonstration does not submit data. Connect the form to an email, CRM or booking backend to send real requests.</p><button className="button button--navy" onClick={() => { setDone(false); setStep(0) }}>Plan another adventure</button></div> : <div className="booking-layout"><div className="booking-panel">
      {step === 0 && <div><span className="eyebrow">Step 1</span><h2>What calls to you?</h2><div className="booking-options">{options.map((item) => <button key={item.slug} className={form.selection === item.slug ? 'selected' : ''} onClick={() => setForm({ ...form, selection: item.slug })}><img src={item.image} alt="" /><span><small>{item.type}</small><strong>{item.shortTitle}</strong><em>{item.duration}</em></span><i><Check /></i></button>)}</div></div>}
      {step === 1 && <div><span className="eyebrow">Step 2</span><h2>Choose a preferred date</h2><p className="lead">Your date is a request until the team checks availability and ocean conditions.</p><label className="date-picker"><CalendarDays /><span><small>Preferred departure</small><input type="date" value={form.date} onChange={(event) => setForm({ ...form, date: event.target.value })} /></span></label><div className="booking-tip"><ShieldCheck /><p><strong>Flexible plans work best.</strong> Add alternatives in your special requests, especially for weather-sensitive experiences.</p></div></div>}
      {step === 2 && <div><span className="eyebrow">Step 3</span><h2>Who’s coming?</h2><div className="guest-counter"><span><strong>Adults</strong><small>Ages 13+</small></span><div><button aria-label="Remove adult" onClick={() => setForm({ ...form, adults: Math.max(1, form.adults - 1) })}><Minus /></button><b>{form.adults}</b><button aria-label="Add adult" onClick={() => setForm({ ...form, adults: form.adults + 1 })}><Plus /></button></div></div><div className="guest-counter"><span><strong>Children</strong><small>Age eligibility varies</small></span><div><button aria-label="Remove child" onClick={() => setForm({ ...form, children: Math.max(0, form.children - 1) })}><Minus /></button><b>{form.children}</b><button aria-label="Add child" onClick={() => setForm({ ...form, children: form.children + 1 })}><Plus /></button></div></div>{confirmedPrice ? <div className="live-price"><span>{guestCount} × ${calculatedPrice.perPerson} per person</span><strong>${calculatedPrice.total} total</strong></div> : <p className="demo-note">{selected.pricing?.status === 'confirmed' ? 'Published rates cover 1–4 guests. Please request a quote for larger groups.' : 'A confirmed price has not yet been supplied for this experience. Please request a quote.'}</p>}</div>}
      {step === 3 && <div><span className="eyebrow">Step 4</span><h2>Make it yours</h2><div className="extras-list">{extras.map(([id, title]) => <button key={id} className={form.extras.includes(id) ? 'selected' : ''} onClick={() => toggle(id)}><span><strong>{title}</strong><small>Subject to confirmation</small></span><em>Price on request</em><i>{form.extras.includes(id) ? <Check /> : <Plus />}</i></button>)}</div></div>}
      {step === 4 && <div><span className="eyebrow">Step 5</span><h2>Where should we reach you?</h2><div className="details-form"><label>Full name<input value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} /></label><div className="field-row"><label>Email<input type="email" value={form.email} onChange={(event) => setForm({ ...form, email: event.target.value })} /></label><label>Phone / WhatsApp<input value={form.phone} onChange={(event) => setForm({ ...form, phone: event.target.value })} /></label></div><label>Hotel / accommodation<input value={form.hotel} onChange={(event) => setForm({ ...form, hotel: event.target.value })} /></label><label>Special requests<textarea rows="4" value={form.requests} onChange={(event) => setForm({ ...form, requests: event.target.value })} /></label></div></div>}
      {step === 5 && <div><span className="eyebrow">Step 6</span><h2>Review your request</h2><div className="review-list"><div><span>Adventure</span><strong>{selected.shortTitle}</strong></div><div><span>Preferred date</span><strong>{form.date || 'Not selected'}</strong></div><div><span>Guests</span><strong>{form.adults} adults{form.children ? `, ${form.children} children` : ''}</strong></div><div><span>Rate</span><strong>{confirmedPrice ? `$${calculatedPrice.perPerson} USD per person` : 'Price on request'}</strong></div><div><span>Total</span><strong>{confirmedPrice ? `$${calculatedPrice.total} USD` : 'Quote required'}</strong></div><div><span>Extras</span><strong>{form.extras.length ? form.extras.map((id) => extras.find((item) => item[0] === id)[1]).join(', ') : 'None'}</strong></div><div><span>Contact</span><strong>{form.name || 'Not provided'} · {form.email || 'No email'}</strong></div></div><div className="booking-tip"><ShieldCheck /><p><strong>This is a request, not a confirmed booking.</strong> Final availability, suitability and any unpriced items will be confirmed before payment.</p></div></div>}
      <div className="booking-actions">{step > 0 ? <button className="text-button" onClick={back}><ArrowLeft /> Back</button> : <span />}<button className="button button--coral" onClick={step === 5 ? () => setDone(true) : next}>{step === 5 ? 'Reserve adventure' : 'Continue'} <ArrowRight /></button></div>
    </div><aside className="booking-summary"><img src={selected.image} alt="" /><span className="eyebrow">Your adventure</span><h3>{selected.shortTitle}</h3><dl><div><dt>Guests</dt><dd>{guestCount}</dd></div><div><dt>Date</dt><dd>{form.date || 'Choose later'}</dd></div><div><dt>Per-person rate</dt><dd>{confirmedPrice ? `$${calculatedPrice.perPerson} USD` : 'On request'}</dd></div><div><dt>Extras</dt><dd>{form.extras.length ? 'On request' : 'None'}</dd></div></dl><div className={`summary-total ${!confirmedPrice ? 'summary-total--quote' : ''}`}><span>{confirmedPrice ? 'Activity total · USD' : 'Pricing'}<small>{confirmedPrice ? `${guestCount} guest${guestCount === 1 ? '' : 's'} × $${calculatedPrice.perPerson}` : 'Contact us for a quote'}</small></span><strong>{confirmedPrice ? `$${calculatedPrice.total}` : 'On request'}</strong></div></aside></div>}
  </div></section></>
}
