import { Clock, Mail, MapPin, MessageCircle, Send } from 'lucide-react'
import { useState } from 'react'
import PageHero from '../components/PageHero'
import { business } from '../config/business'
import { media } from '../data/media'

export default function Contact() {
  const [sent, setSent] = useState(false)
  const submit = (event) => { event.preventDefault(); setSent(true) }
  return <><PageHero compact eyebrow="Let’s plan your ocean day" title="Start with a conversation." copy="Tell us what excites you, and we’ll help shape the right Mirissa experience." image={media.kayak} /><section className="section"><div className="container contact-grid"><div><span className="eyebrow">Get in touch</span><h2>We’re here to make planning easy.</h2><p className="lead">Share your dates, group and comfort in the water. The more we know, the better we can guide you.</p><div className="contact-methods"><div><Mail /><span><small>Email</small><strong>{business.email}</strong><em>Placeholder address</em></span></div><div><MessageCircle /><span><small>WhatsApp</small><strong>Number pending</strong><em>Live chat hidden until configured</em></span></div><div><MapPin /><span><small>Meeting point</small><strong>Mirissa, Sri Lanka</strong><em>Exact location shared after confirmation</em></span></div><div><Clock /><span><small>Response time</small><strong>To be confirmed</strong><em>Add normal support hours here</em></span></div></div></div><form className="contact-form" onSubmit={submit}><div className="field-row"><label>First name<input required name="firstName" /></label><label>Last name<input required name="lastName" /></label></div><label>Email address<input required type="email" name="email" /></label><label>WhatsApp / phone<input type="tel" name="phone" /></label><label>What would you like to explore?<select name="interest"><option>Whale watching</option><option>Diving</option><option>Snorkeling</option><option>Kayaking</option><option>Surf lessons</option><option>Multi-day package</option></select></label><label>Tell us more<textarea rows="5" placeholder="Travel dates, group size, experience level or any questions…" /></label><button className="button button--coral">Send enquiry <Send size={17} /></button>{sent && <p className="form-success" role="status">Thanks—this demo form is ready to connect to your email or CRM backend.</p>}</form></div></section></>
}
